riot:
  api:
    key: ${riot.api.key}
    url:
      kr: https://kr.api.riotgames.com
      asia: https://asia.api.riotgames.com
      cdn: https://ddragon.leagueoflegends.com/cdn/
  versions: 13.16.1
logging:
  level:
    com:
      immersion:
        riot: DEBUG
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            dismiss404: true
            loggerLevel: FULL
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
cors:
  allow-methods : ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
  allow-origins : ['http://localhost:3000']
